name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Super das du mir ein Issue schreibts"
        pr-message: " ... irgendwas"

    - uses: cinotify/github-action@main
      with:
        to: 'edward.fetzer@gmx.de'
        subject: 'Es gab einen Pull request oder ein issue'
        body: 'HALLLO ########## :)'
